// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: changes.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createChangeRequest = `-- name: CreateChangeRequest :one
INSERT INTO change_requests (flag_id, environment_id, author_id, base_version, proposed, comment)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, flag_id, environment_id, author_id, status, base_version, proposed, comment, reviewer_id, review_comment, reviewed_at, created_at
`

type CreateChangeRequestParams struct {
	FlagID        uuid.UUID
	EnvironmentID uuid.UUID
	AuthorID      uuid.UUID
	BaseVersion   int32
	Proposed      json.RawMessage
	Comment       string
}

func (q *Queries) CreateChangeRequest(ctx context.Context, arg CreateChangeRequestParams) (ChangeRequest, error) {
	row := q.db.QueryRow(ctx, createChangeRequest,
		arg.FlagID,
		arg.EnvironmentID,
		arg.AuthorID,
		arg.BaseVersion,
		arg.Proposed,
		arg.Comment,
	)
	var i ChangeRequest
	err := row.Scan(
		&i.ID,
		&i.FlagID,
		&i.EnvironmentID,
		&i.AuthorID,
		&i.Status,
		&i.BaseVersion,
		&i.Proposed,
		&i.Comment,
		&i.ReviewerID,
		&i.ReviewComment,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getChangeRequest = `-- name: GetChangeRequest :one
SELECT cr.id, cr.flag_id, cr.environment_id, cr.author_id, cr.status, cr.base_version, cr.proposed, cr.comment, cr.reviewer_id, cr.review_comment, cr.reviewed_at, cr.created_at, f.key AS flag_key, e.key AS environment_key, a.name AS author_name, r.name AS reviewer_name
FROM change_requests cr
JOIN flags f ON f.id = cr.flag_id
JOIN environments e ON e.id = cr.environment_id
JOIN users a ON a.id = cr.author_id
LEFT JOIN users r ON r.id = cr.reviewer_id
WHERE cr.id = $1 AND f.project_id = $2
`

type GetChangeRequestParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

type GetChangeRequestRow struct {
	ID             uuid.UUID
	FlagID         uuid.UUID
	EnvironmentID  uuid.UUID
	AuthorID       uuid.UUID
	Status         ChangeStatus
	BaseVersion    int32
	Proposed       json.RawMessage
	Comment        string
	ReviewerID     *uuid.UUID
	ReviewComment  string
	ReviewedAt     *time.Time
	CreatedAt      time.Time
	FlagKey        string
	EnvironmentKey string
	AuthorName     string
	ReviewerName   *string
}

func (q *Queries) GetChangeRequest(ctx context.Context, arg GetChangeRequestParams) (GetChangeRequestRow, error) {
	row := q.db.QueryRow(ctx, getChangeRequest, arg.ID, arg.ProjectID)
	var i GetChangeRequestRow
	err := row.Scan(
		&i.ID,
		&i.FlagID,
		&i.EnvironmentID,
		&i.AuthorID,
		&i.Status,
		&i.BaseVersion,
		&i.Proposed,
		&i.Comment,
		&i.ReviewerID,
		&i.ReviewComment,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.FlagKey,
		&i.EnvironmentKey,
		&i.AuthorName,
		&i.ReviewerName,
	)
	return i, err
}

const listChangeRequests = `-- name: ListChangeRequests :many
SELECT cr.id, cr.flag_id, cr.environment_id, cr.author_id, cr.status, cr.base_version, cr.proposed, cr.comment, cr.reviewer_id, cr.review_comment, cr.reviewed_at, cr.created_at, f.key AS flag_key, e.key AS environment_key, a.name AS author_name, r.name AS reviewer_name
FROM change_requests cr
JOIN flags f ON f.id = cr.flag_id
JOIN environments e ON e.id = cr.environment_id
JOIN users a ON a.id = cr.author_id
LEFT JOIN users r ON r.id = cr.reviewer_id
WHERE f.project_id = $1
  AND ($2::change_status IS NULL OR cr.status = $2)
ORDER BY cr.created_at DESC
LIMIT 200
`

type ListChangeRequestsParams struct {
	ProjectID uuid.UUID
	Status    NullChangeStatus
}

type ListChangeRequestsRow struct {
	ID             uuid.UUID
	FlagID         uuid.UUID
	EnvironmentID  uuid.UUID
	AuthorID       uuid.UUID
	Status         ChangeStatus
	BaseVersion    int32
	Proposed       json.RawMessage
	Comment        string
	ReviewerID     *uuid.UUID
	ReviewComment  string
	ReviewedAt     *time.Time
	CreatedAt      time.Time
	FlagKey        string
	EnvironmentKey string
	AuthorName     string
	ReviewerName   *string
}

func (q *Queries) ListChangeRequests(ctx context.Context, arg ListChangeRequestsParams) ([]ListChangeRequestsRow, error) {
	rows, err := q.db.Query(ctx, listChangeRequests, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangeRequestsRow
	for rows.Next() {
		var i ListChangeRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.FlagID,
			&i.EnvironmentID,
			&i.AuthorID,
			&i.Status,
			&i.BaseVersion,
			&i.Proposed,
			&i.Comment,
			&i.ReviewerID,
			&i.ReviewComment,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.FlagKey,
			&i.EnvironmentKey,
			&i.AuthorName,
			&i.ReviewerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewChangeRequest = `-- name: ReviewChangeRequest :one
UPDATE change_requests
SET status = $2, reviewer_id = $3, review_comment = $4, reviewed_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, flag_id, environment_id, author_id, status, base_version, proposed, comment, reviewer_id, review_comment, reviewed_at, created_at
`

type ReviewChangeRequestParams struct {
	ID            uuid.UUID
	Status        ChangeStatus
	ReviewerID    *uuid.UUID
	ReviewComment string
}

func (q *Queries) ReviewChangeRequest(ctx context.Context, arg ReviewChangeRequestParams) (ChangeRequest, error) {
	row := q.db.QueryRow(ctx, reviewChangeRequest,
		arg.ID,
		arg.Status,
		arg.ReviewerID,
		arg.ReviewComment,
	)
	var i ChangeRequest
	err := row.Scan(
		&i.ID,
		&i.FlagID,
		&i.EnvironmentID,
		&i.AuthorID,
		&i.Status,
		&i.BaseVersion,
		&i.Proposed,
		&i.Comment,
		&i.ReviewerID,
		&i.ReviewComment,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}
