// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addExposures = `-- name: AddExposures :exec
INSERT INTO exposure_counts (flag_id, environment_id, variant, bucket, count)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (flag_id, environment_id, bucket, variant)
DO UPDATE SET count = exposure_counts.count + EXCLUDED.count
`

type AddExposuresParams struct {
	FlagID        uuid.UUID
	EnvironmentID uuid.UUID
	Variant       string
	Bucket        time.Time
	Count         int64
}

func (q *Queries) AddExposures(ctx context.Context, arg AddExposuresParams) error {
	_, err := q.db.Exec(ctx, addExposures,
		arg.FlagID,
		arg.EnvironmentID,
		arg.Variant,
		arg.Bucket,
		arg.Count,
	)
	return err
}

const claimOutbox = `-- name: ClaimOutbox :many
SELECT id, topic, key, payload, created_at, published_at FROM outbox
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// SKIP LOCKED lets several relays run without waiting on each other.
func (q *Queries) ClaimOutbox(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, claimOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Key,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exposureCounts = `-- name: ExposureCounts :many
SELECT bucket, variant, count FROM exposure_counts
WHERE flag_id = $1 AND environment_id = $2 AND bucket >= $3 AND bucket < $4
ORDER BY bucket, variant
`

type ExposureCountsParams struct {
	FlagID        uuid.UUID
	EnvironmentID uuid.UUID
	Since         time.Time
	Until         time.Time
}

type ExposureCountsRow struct {
	Bucket  time.Time
	Variant string
	Count   int64
}

func (q *Queries) ExposureCounts(ctx context.Context, arg ExposureCountsParams) ([]ExposureCountsRow, error) {
	rows, err := q.db.Query(ctx, exposureCounts,
		arg.FlagID,
		arg.EnvironmentID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExposureCountsRow
	for rows.Next() {
		var i ExposureCountsRow
		if err := rows.Scan(&i.Bucket, &i.Variant, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (actor_id, action, project_id, entity_type, entity_id, summary, data)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditEventParams struct {
	ActorID    *uuid.UUID
	Action     string
	ProjectID  *uuid.UUID
	EntityType string
	EntityID   *uuid.UUID
	Summary    string
	Data       json.RawMessage
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ActorID,
		arg.Action,
		arg.ProjectID,
		arg.EntityType,
		arg.EntityID,
		arg.Summary,
		arg.Data,
	)
	return err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (topic, key, payload) VALUES ($1, $2, $3)
`

type InsertOutboxParams struct {
	Topic   string
	Key     string
	Payload json.RawMessage
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.Topic, arg.Key, arg.Payload)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT ae.id, ae.actor_id, ae.action, ae.project_id, ae.entity_type, ae.entity_id, ae.summary, ae.data, ae.created_at, u.name AS actor_name, u.email AS actor_email
FROM audit_events ae
LEFT JOIN users u ON u.id = ae.actor_id
WHERE ($1::uuid IS NULL OR ae.project_id = $1)
  AND ($2::bigint IS NULL OR ae.id < $2)
ORDER BY ae.id DESC
LIMIT $3
`

type ListAuditEventsParams struct {
	ProjectID *uuid.UUID
	Before    *int64
	MaxRows   int32
}

type ListAuditEventsRow struct {
	ID         int64
	ActorID    *uuid.UUID
	Action     string
	ProjectID  *uuid.UUID
	EntityType string
	EntityID   *uuid.UUID
	Summary    string
	Data       json.RawMessage
	CreatedAt  time.Time
	ActorName  *string
	ActorEmail *string
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.ProjectID, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditEventsRow
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.ProjectID,
			&i.EntityType,
			&i.EntityID,
			&i.Summary,
			&i.Data,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox SET published_at = now() WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, ids)
	return err
}
