// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: flags.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createFlag = `-- name: CreateFlag :one
INSERT INTO flags (project_id, key, name, description, kind, tags, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, key, name, description, kind, tags, created_by, created_at, updated_at, archived_at
`

type CreateFlagParams struct {
	ProjectID   uuid.UUID
	Key         string
	Name        string
	Description string
	Kind        FlagKind
	Tags        []string
	CreatedBy   *uuid.UUID
}

func (q *Queries) CreateFlag(ctx context.Context, arg CreateFlagParams) (Flag, error) {
	row := q.db.QueryRow(ctx, createFlag,
		arg.ProjectID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Kind,
		arg.Tags,
		arg.CreatedBy,
	)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Tags,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createFlagConfig = `-- name: CreateFlagConfig :one
INSERT INTO flag_configs (flag_id, environment_id, enabled, default_variant, off_variant, rules, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING flag_id, environment_id, enabled, default_variant, off_variant, rules, version, updated_by, updated_at
`

type CreateFlagConfigParams struct {
	FlagID         uuid.UUID
	EnvironmentID  uuid.UUID
	Enabled        bool
	DefaultVariant string
	OffVariant     string
	Rules          json.RawMessage
	UpdatedBy      *uuid.UUID
}

func (q *Queries) CreateFlagConfig(ctx context.Context, arg CreateFlagConfigParams) (FlagConfig, error) {
	row := q.db.QueryRow(ctx, createFlagConfig,
		arg.FlagID,
		arg.EnvironmentID,
		arg.Enabled,
		arg.DefaultVariant,
		arg.OffVariant,
		arg.Rules,
		arg.UpdatedBy,
	)
	var i FlagConfig
	err := row.Scan(
		&i.FlagID,
		&i.EnvironmentID,
		&i.Enabled,
		&i.DefaultVariant,
		&i.OffVariant,
		&i.Rules,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createVariant = `-- name: CreateVariant :one
INSERT INTO flag_variants (flag_id, key, value, description, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, flag_id, key, value, description, position
`

type CreateVariantParams struct {
	FlagID      uuid.UUID
	Key         string
	Value       json.RawMessage
	Description string
	Position    int32
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (FlagVariant, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.FlagID,
		arg.Key,
		arg.Value,
		arg.Description,
		arg.Position,
	)
	var i FlagVariant
	err := row.Scan(
		&i.ID,
		&i.FlagID,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Position,
	)
	return i, err
}

const environmentSnapshot = `-- name: EnvironmentSnapshot :many
SELECT f.id, f.key, f.kind, c.enabled, c.default_variant, c.off_variant, c.rules, c.version,
       (SELECT jsonb_object_agg(v.key, v.value) FROM flag_variants v WHERE v.flag_id = f.id)::jsonb AS variants
FROM flags f
JOIN flag_configs c ON c.flag_id = f.id
WHERE c.environment_id = $1 AND f.archived_at IS NULL
ORDER BY f.key
`

type EnvironmentSnapshotRow struct {
	ID             uuid.UUID
	Key            string
	Kind           FlagKind
	Enabled        bool
	DefaultVariant string
	OffVariant     string
	Rules          json.RawMessage
	Version        int32
	Variants       json.RawMessage
}

// Everything an SDK needs to evaluate one environment's flags.
func (q *Queries) EnvironmentSnapshot(ctx context.Context, environmentID uuid.UUID) ([]EnvironmentSnapshotRow, error) {
	rows, err := q.db.Query(ctx, environmentSnapshot, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvironmentSnapshotRow
	for rows.Next() {
		var i EnvironmentSnapshotRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Kind,
			&i.Enabled,
			&i.DefaultVariant,
			&i.OffVariant,
			&i.Rules,
			&i.Version,
			&i.Variants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flagIDsByKey = `-- name: FlagIDsByKey :many
SELECT id, key FROM flags WHERE project_id = $1 AND key = ANY($2::text[])
`

type FlagIDsByKeyParams struct {
	ProjectID uuid.UUID
	Keys      []string
}

type FlagIDsByKeyRow struct {
	ID  uuid.UUID
	Key string
}

func (q *Queries) FlagIDsByKey(ctx context.Context, arg FlagIDsByKeyParams) ([]FlagIDsByKeyRow, error) {
	rows, err := q.db.Query(ctx, flagIDsByKey, arg.ProjectID, arg.Keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlagIDsByKeyRow
	for rows.Next() {
		var i FlagIDsByKeyRow
		if err := rows.Scan(&i.ID, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlag = `-- name: GetFlag :one
SELECT id, project_id, key, name, description, kind, tags, created_by, created_at, updated_at, archived_at FROM flags WHERE project_id = $1 AND key = $2
`

type GetFlagParams struct {
	ProjectID uuid.UUID
	Key       string
}

func (q *Queries) GetFlag(ctx context.Context, arg GetFlagParams) (Flag, error) {
	row := q.db.QueryRow(ctx, getFlag, arg.ProjectID, arg.Key)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Tags,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getFlagConfig = `-- name: GetFlagConfig :one
SELECT flag_id, environment_id, enabled, default_variant, off_variant, rules, version, updated_by, updated_at FROM flag_configs WHERE flag_id = $1 AND environment_id = $2
`

type GetFlagConfigParams struct {
	FlagID        uuid.UUID
	EnvironmentID uuid.UUID
}

func (q *Queries) GetFlagConfig(ctx context.Context, arg GetFlagConfigParams) (FlagConfig, error) {
	row := q.db.QueryRow(ctx, getFlagConfig, arg.FlagID, arg.EnvironmentID)
	var i FlagConfig
	err := row.Scan(
		&i.FlagID,
		&i.EnvironmentID,
		&i.Enabled,
		&i.DefaultVariant,
		&i.OffVariant,
		&i.Rules,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listFlagConfigs = `-- name: ListFlagConfigs :many
SELECT c.flag_id, c.environment_id, c.enabled, c.default_variant, c.off_variant, c.rules, c.version, c.updated_by, c.updated_at, e.key AS environment_key
FROM flag_configs c
JOIN environments e ON e.id = c.environment_id
WHERE c.flag_id = ANY($1::uuid[])
ORDER BY e.position, e.key
`

type ListFlagConfigsRow struct {
	FlagID         uuid.UUID
	EnvironmentID  uuid.UUID
	Enabled        bool
	DefaultVariant string
	OffVariant     string
	Rules          json.RawMessage
	Version        int32
	UpdatedBy      *uuid.UUID
	UpdatedAt      time.Time
	EnvironmentKey string
}

func (q *Queries) ListFlagConfigs(ctx context.Context, flagIds []uuid.UUID) ([]ListFlagConfigsRow, error) {
	rows, err := q.db.Query(ctx, listFlagConfigs, flagIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlagConfigsRow
	for rows.Next() {
		var i ListFlagConfigsRow
		if err := rows.Scan(
			&i.FlagID,
			&i.EnvironmentID,
			&i.Enabled,
			&i.DefaultVariant,
			&i.OffVariant,
			&i.Rules,
			&i.Version,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.EnvironmentKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlags = `-- name: ListFlags :many
SELECT id, project_id, key, name, description, kind, tags, created_by, created_at, updated_at, archived_at FROM flags
WHERE project_id = $1 AND ($2::boolean OR archived_at IS NULL)
ORDER BY key
`

type ListFlagsParams struct {
	ProjectID       uuid.UUID
	IncludeArchived bool
}

func (q *Queries) ListFlags(ctx context.Context, arg ListFlagsParams) ([]Flag, error) {
	rows, err := q.db.Query(ctx, listFlags, arg.ProjectID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flag
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Kind,
			&i.Tags,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariants = `-- name: ListVariants :many
SELECT id, flag_id, key, value, description, position FROM flag_variants WHERE flag_id = ANY($1::uuid[]) ORDER BY flag_id, position
`

func (q *Queries) ListVariants(ctx context.Context, flagIds []uuid.UUID) ([]FlagVariant, error) {
	rows, err := q.db.Query(ctx, listVariants, flagIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlagVariant
	for rows.Next() {
		var i FlagVariant
		if err := rows.Scan(
			&i.ID,
			&i.FlagID,
			&i.Key,
			&i.Value,
			&i.Description,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFlagArchived = `-- name: SetFlagArchived :one
UPDATE flags
SET archived_at = CASE WHEN $2::boolean THEN now() END, updated_at = now()
WHERE id = $1
RETURNING id, project_id, key, name, description, kind, tags, created_by, created_at, updated_at, archived_at
`

type SetFlagArchivedParams struct {
	ID       uuid.UUID
	Archived bool
}

func (q *Queries) SetFlagArchived(ctx context.Context, arg SetFlagArchivedParams) (Flag, error) {
	row := q.db.QueryRow(ctx, setFlagArchived, arg.ID, arg.Archived)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Tags,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateFlag = `-- name: UpdateFlag :one
UPDATE flags SET name = $2, description = $3, tags = $4, updated_at = now()
WHERE id = $1
RETURNING id, project_id, key, name, description, kind, tags, created_by, created_at, updated_at, archived_at
`

type UpdateFlagParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	Tags        []string
}

func (q *Queries) UpdateFlag(ctx context.Context, arg UpdateFlagParams) (Flag, error) {
	row := q.db.QueryRow(ctx, updateFlag,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Tags,
	)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Tags,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateFlagConfig = `-- name: UpdateFlagConfig :one
UPDATE flag_configs
SET enabled = $3, default_variant = $4, off_variant = $5, rules = $6,
    version = version + 1, updated_by = $7, updated_at = now()
WHERE flag_id = $1 AND environment_id = $2 AND version = $8
RETURNING flag_id, environment_id, enabled, default_variant, off_variant, rules, version, updated_by, updated_at
`

type UpdateFlagConfigParams struct {
	FlagID         uuid.UUID
	EnvironmentID  uuid.UUID
	Enabled        bool
	DefaultVariant string
	OffVariant     string
	Rules          json.RawMessage
	UpdatedBy      *uuid.UUID
	BaseVersion    int32
}

// Applies only if the config is still at the version the change was based on.
func (q *Queries) UpdateFlagConfig(ctx context.Context, arg UpdateFlagConfigParams) (FlagConfig, error) {
	row := q.db.QueryRow(ctx, updateFlagConfig,
		arg.FlagID,
		arg.EnvironmentID,
		arg.Enabled,
		arg.DefaultVariant,
		arg.OffVariant,
		arg.Rules,
		arg.UpdatedBy,
		arg.BaseVersion,
	)
	var i FlagConfig
	err := row.Scan(
		&i.FlagID,
		&i.EnvironmentID,
		&i.Enabled,
		&i.DefaultVariant,
		&i.OffVariant,
		&i.Rules,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
