// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ChangeStatus string

const (
	ChangeStatusPending    ChangeStatus = "pending"
	ChangeStatusApplied    ChangeStatus = "applied"
	ChangeStatusRejected   ChangeStatus = "rejected"
	ChangeStatusCancelled  ChangeStatus = "cancelled"
	ChangeStatusConflicted ChangeStatus = "conflicted"
)

func (e *ChangeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChangeStatus(s)
	case string:
		*e = ChangeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ChangeStatus: %T", src)
	}
	return nil
}

type NullChangeStatus struct {
	ChangeStatus ChangeStatus
	Valid        bool // Valid is true if ChangeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChangeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ChangeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChangeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChangeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChangeStatus), nil
}

func (e ChangeStatus) Valid() bool {
	switch e {
	case ChangeStatusPending,
		ChangeStatusApplied,
		ChangeStatusRejected,
		ChangeStatusCancelled,
		ChangeStatusConflicted:
		return true
	}
	return false
}

func AllChangeStatusValues() []ChangeStatus {
	return []ChangeStatus{
		ChangeStatusPending,
		ChangeStatusApplied,
		ChangeStatusRejected,
		ChangeStatusCancelled,
		ChangeStatusConflicted,
	}
}

type FlagKind string

const (
	FlagKindBoolean FlagKind = "boolean"
	FlagKindString  FlagKind = "string"
	FlagKindNumber  FlagKind = "number"
	FlagKindJson    FlagKind = "json"
)

func (e *FlagKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FlagKind(s)
	case string:
		*e = FlagKind(s)
	default:
		return fmt.Errorf("unsupported scan type for FlagKind: %T", src)
	}
	return nil
}

type NullFlagKind struct {
	FlagKind FlagKind
	Valid    bool // Valid is true if FlagKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFlagKind) Scan(value interface{}) error {
	if value == nil {
		ns.FlagKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FlagKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFlagKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FlagKind), nil
}

func (e FlagKind) Valid() bool {
	switch e {
	case FlagKindBoolean,
		FlagKindString,
		FlagKindNumber,
		FlagKindJson:
		return true
	}
	return false
}

func AllFlagKindValues() []FlagKind {
	return []FlagKind{
		FlagKindBoolean,
		FlagKindString,
		FlagKindNumber,
		FlagKindJson,
	}
}

type TokenPurpose string

const (
	TokenPurposeInvite        TokenPurpose = "invite"
	TokenPurposePasswordReset TokenPurpose = "password_reset"
)

func (e *TokenPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TokenPurpose(s)
	case string:
		*e = TokenPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for TokenPurpose: %T", src)
	}
	return nil
}

type NullTokenPurpose struct {
	TokenPurpose TokenPurpose
	Valid        bool // Valid is true if TokenPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTokenPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.TokenPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TokenPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTokenPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TokenPurpose), nil
}

func (e TokenPurpose) Valid() bool {
	switch e {
	case TokenPurposeInvite,
		TokenPurposePasswordReset:
		return true
	}
	return false
}

func AllTokenPurposeValues() []TokenPurpose {
	return []TokenPurpose{
		TokenPurposeInvite,
		TokenPurposePasswordReset,
	}
}

type UserRole string

const (
	UserRoleViewer   UserRole = "viewer"
	UserRoleEditor   UserRole = "editor"
	UserRoleApprover UserRole = "approver"
	UserRoleAdmin    UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

func (e UserRole) Valid() bool {
	switch e {
	case UserRoleViewer,
		UserRoleEditor,
		UserRoleApprover,
		UserRoleAdmin:
		return true
	}
	return false
}

func AllUserRoleValues() []UserRole {
	return []UserRole{
		UserRoleViewer,
		UserRoleEditor,
		UserRoleApprover,
		UserRoleAdmin,
	}
}

type AuditEvent struct {
	ID         int64
	ActorID    *uuid.UUID
	Action     string
	ProjectID  *uuid.UUID
	EntityType string
	EntityID   *uuid.UUID
	Summary    string
	Data       json.RawMessage
	CreatedAt  time.Time
}

type ChangeRequest struct {
	ID            uuid.UUID
	FlagID        uuid.UUID
	EnvironmentID uuid.UUID
	AuthorID      uuid.UUID
	Status        ChangeStatus
	BaseVersion   int32
	Proposed      json.RawMessage
	Comment       string
	ReviewerID    *uuid.UUID
	ReviewComment string
	ReviewedAt    *time.Time
	CreatedAt     time.Time
}

type Environment struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	Key              string
	Name             string
	RequiresApproval bool
	Position         int32
	CreatedAt        time.Time
}

type ExposureCount struct {
	FlagID        uuid.UUID
	EnvironmentID uuid.UUID
	Variant       string
	Bucket        time.Time
	Count         int64
}

type Flag struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Key         string
	Name        string
	Description string
	Kind        FlagKind
	Tags        []string
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ArchivedAt  *time.Time
}

type FlagConfig struct {
	FlagID         uuid.UUID
	EnvironmentID  uuid.UUID
	Enabled        bool
	DefaultVariant string
	OffVariant     string
	Rules          json.RawMessage
	Version        int32
	UpdatedBy      *uuid.UUID
	UpdatedAt      time.Time
}

type FlagVariant struct {
	ID          uuid.UUID
	FlagID      uuid.UUID
	Key         string
	Value       json.RawMessage
	Description string
	Position    int32
}

type Outbox struct {
	ID          int64
	Topic       string
	Key         string
	Payload     json.RawMessage
	CreatedAt   time.Time
	PublishedAt *time.Time
}

type Project struct {
	ID          uuid.UUID
	Key         string
	Name        string
	Description string
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
}

type SdkKey struct {
	ID            uuid.UUID
	EnvironmentID uuid.UUID
	Name          string
	Prefix        string
	KeyHash       []byte
	CreatedBy     *uuid.UUID
	CreatedAt     time.Time
	RevokedAt     *time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	Name         string
	Role         UserRole
	PasswordHash *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DisabledAt   *time.Time
}

type UserToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Purpose   TokenPurpose
	TokenHash []byte
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedBy *uuid.UUID
	CreatedAt time.Time
}
