// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createConfigsForEnvironment = `-- name: CreateConfigsForEnvironment :exec
INSERT INTO flag_configs (flag_id, environment_id, enabled, default_variant, off_variant, updated_by)
SELECT DISTINCT ON (c.flag_id) c.flag_id, $1::uuid, false, c.default_variant, c.off_variant, $2::uuid
FROM flag_configs c
JOIN environments e ON e.id = c.environment_id
WHERE e.project_id = $3::uuid AND e.id <> $1::uuid
ORDER BY c.flag_id, e.position
`

type CreateConfigsForEnvironmentParams struct {
	EnvironmentID uuid.UUID
	UpdatedBy     *uuid.UUID
	ProjectID     uuid.UUID
}

// A new environment starts with every flag off, serving the same variants
// as the project's first environment.
func (q *Queries) CreateConfigsForEnvironment(ctx context.Context, arg CreateConfigsForEnvironmentParams) error {
	_, err := q.db.Exec(ctx, createConfigsForEnvironment, arg.EnvironmentID, arg.UpdatedBy, arg.ProjectID)
	return err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (project_id, key, name, requires_approval, position)
VALUES ($1, $2, $3, $4, (SELECT coalesce(max(position), -1) + 1 FROM environments WHERE project_id = $1))
RETURNING id, project_id, key, name, requires_approval, position, created_at
`

type CreateEnvironmentParams struct {
	ProjectID        uuid.UUID
	Key              string
	Name             string
	RequiresApproval bool
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.ProjectID,
		arg.Key,
		arg.Name,
		arg.RequiresApproval,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.RequiresApproval,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (key, name, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, key, name, description, created_by, created_at
`

type CreateProjectParams struct {
	Key         string
	Name        string
	Description string
	CreatedBy   *uuid.UUID
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createSDKKey = `-- name: CreateSDKKey :one
INSERT INTO sdk_keys (environment_id, name, prefix, key_hash, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, environment_id, name, prefix, key_hash, created_by, created_at, revoked_at
`

type CreateSDKKeyParams struct {
	EnvironmentID uuid.UUID
	Name          string
	Prefix        string
	KeyHash       []byte
	CreatedBy     *uuid.UUID
}

func (q *Queries) CreateSDKKey(ctx context.Context, arg CreateSDKKeyParams) (SdkKey, error) {
	row := q.db.QueryRow(ctx, createSDKKey,
		arg.EnvironmentID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
		arg.CreatedBy,
	)
	var i SdkKey
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const environmentForSDKKey = `-- name: EnvironmentForSDKKey :one
SELECT e.id AS environment_id, e.key AS environment_key, p.id AS project_id, p.key AS project_key
FROM sdk_keys k
JOIN environments e ON e.id = k.environment_id
JOIN projects p ON p.id = e.project_id
WHERE k.key_hash = $1 AND k.revoked_at IS NULL
`

type EnvironmentForSDKKeyRow struct {
	EnvironmentID  uuid.UUID
	EnvironmentKey string
	ProjectID      uuid.UUID
	ProjectKey     string
}

func (q *Queries) EnvironmentForSDKKey(ctx context.Context, keyHash []byte) (EnvironmentForSDKKeyRow, error) {
	row := q.db.QueryRow(ctx, environmentForSDKKey, keyHash)
	var i EnvironmentForSDKKeyRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.EnvironmentKey,
		&i.ProjectID,
		&i.ProjectKey,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, project_id, key, name, requires_approval, position, created_at FROM environments WHERE project_id = $1 AND key = $2
`

type GetEnvironmentParams struct {
	ProjectID uuid.UUID
	Key       string
}

func (q *Queries) GetEnvironment(ctx context.Context, arg GetEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, arg.ProjectID, arg.Key)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.RequiresApproval,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, key, name, description, created_by, created_at FROM projects WHERE key = $1
`

func (q *Queries) GetProjectByKey(ctx context.Context, key string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByKey, key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, project_id, key, name, requires_approval, position, created_at FROM environments WHERE project_id = $1 ORDER BY position, key
`

func (q *Queries) ListEnvironments(ctx context.Context, projectID uuid.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.RequiresApproval,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, key, name, description, created_by, created_at FROM projects ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSDKKeys = `-- name: ListSDKKeys :many
SELECT id, environment_id, name, prefix, key_hash, created_by, created_at, revoked_at FROM sdk_keys WHERE environment_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSDKKeys(ctx context.Context, environmentID uuid.UUID) ([]SdkKey, error) {
	rows, err := q.db.Query(ctx, listSDKKeys, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SdkKey
	for rows.Next() {
		var i SdkKey
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.Prefix,
			&i.KeyHash,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSDKKey = `-- name: RevokeSDKKey :one
UPDATE sdk_keys SET revoked_at = now()
WHERE id = $1 AND environment_id = $2 AND revoked_at IS NULL
RETURNING id, environment_id, name, prefix, key_hash, created_by, created_at, revoked_at
`

type RevokeSDKKeyParams struct {
	ID            uuid.UUID
	EnvironmentID uuid.UUID
}

func (q *Queries) RevokeSDKKey(ctx context.Context, arg RevokeSDKKeyParams) (SdkKey, error) {
	row := q.db.QueryRow(ctx, revokeSDKKey, arg.ID, arg.EnvironmentID)
	var i SdkKey
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateEnvironment = `-- name: UpdateEnvironment :one
UPDATE environments SET name = $2, requires_approval = $3 WHERE id = $1 RETURNING id, project_id, key, name, requires_approval, position, created_at
`

type UpdateEnvironmentParams struct {
	ID               uuid.UUID
	Name             string
	RequiresApproval bool
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironment, arg.ID, arg.Name, arg.RequiresApproval)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.RequiresApproval,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET name = $2, description = $3 WHERE id = $1 RETURNING id, key, name, description, created_by, created_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID
	Name        string
	Description string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
